version: "3"

services:
  chweb_app:
    container_name: chweb_app
    restart: always
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    links:
      - chweb_mongo
    depends_on:
      - chweb_mongo
    networks:
      - chweb-network
    command: ./docker/wait-for.sh chweb_mongo:27017 -- ./docker/launch.sh

  chweb_mongo:
    container_name: chweb_mongo
    image: mongo:latest
    networks:
      - chweb-network
    volumes:
      - ./data:/data/db

networks:
  chweb-network:
    driver: bridge
