version: "3"

services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - chweb-network
    command: ./docker/wait-for.sh mongo:27017 -- ./docker/launch.sh

  mongo:
    container_name: mongo
    image: mongo:latest
    networks:
      - chweb-network
    volumes:
      - ./data:/data/db

networks:
  chweb-network:
    driver: bridge
